### ISSUE TITLE
Update the environtment variable

### ISSUE THREAD

**Issue by ianrussel** [pytest-dev/pytest-env#17]
HI, I have a scenario to test failing auth by updating the variable set in pytest.ini

          env = 
                API_TOKEN=1234correct

In some class

          load_env()
          TOKEN = os.getenv('API_TOKEN')

Now in test I would like to modify its value so the authentication will fail

    test_auth.py
       
       def test_it(monkeypatch):
            os.unsetenv("API_TOKEN")
            print(os.getenv('API_TOKEN')) // its still there
            monkeypatch.setenv("API_TOKEN", 1234wrong)

**Comment by gaborbernat** [comment]
Monkey patch.delenv is what you're looking for
