### ISSUE TITLE
Bug: JSON unsupported

### ISSUE THREAD

**Issue by Elijas** [pytest-dev/pytest-env#2]
To keep it DRY, I'll put a reference to the original issue:

https://github.com/MobileDynasty/pytest-env/issues/11

There's is also a PR with a fix:

https://github.com/MobileDynasty/pytest-env/pull/12

**Comment by gaborbernat** [comment]
A pull request is welcomed to address it. 👍

**Comment by Elijas** [comment]
> A pull request is welcomed to address it. 👍

The PR is available here:

https://github.com/MobileDynasty/pytest-env/pull/12

Unfortunately I'm away from my computer (responding over phone) and will be for the foreseeable future.

Could you maybe git cherry-pick the commit or just copy-paste the changes?

**Comment by gaborbernat** [comment]
It's alright. We'll wait until you're back. Also need to add tests now.

**Comment by Elijas** [comment]
> It's alright. We'll wait until you're back. Also need to add tests now.

Completed it: https://github.com/pytest-dev/pytest-env/pull/5

I did not see any tests written for the package so far, so covering the whole package with unit tests is out of scope for this PR. Once the package has tests, adding tests for this package will be super straighforward.

**Comment by gaborbernat** [comment]
> I did not see any tests written for the package so far, so covering the whole package with unit tests is out of scope for this PR.

Strongly disagree.

**Comment by Elijas** [comment]
Thanks for providing an expected framework for unit testing! Now adding tests for the package is really straightforward. I did add the tests, and also tried to improve a little more on the framework itself, as the current framework introduced a lot of boilerplate code and files. Please take a look: #8

**Comment by Elijas** [comment]
Fixed with #9
