### ISSUE TITLE
How to override docker environment variables?

### ISSUE THREAD

**Issue by stevenengland** [pytest-dev/pytest-env#29]
Hi at all,

thanks for this awesome helper library. I managed to get everything working for a local installation. There a environment variable is set successfully when running pytest. Now I want to setup a docker based test environment. The docker image sets this environment variable upfront and I want pytest-env to override it. 

Here is the setup.cfg that is working within the non docker installation:
```
[tool:pytest]
# Set environment vars for test runs only (needs pytest-env package)
env =
    DJANGO_ENV=test
```
The same setup.cfg has no effect when running pytest in docker.

Since the environment variable is set via ENV command in a Dockerfile, it has the least precedence and should be easily overridable. 

Would you say that this scenario is valid and I need to investigate further, where the issue comes from? Any ideas what I might check?

**Comment by gaborbernat** [comment]
This should work. You must be missing something somewhere, but I'm unable to help with the limited information you provided.
