### ISSUE TITLE
Support/document using with Pyproject.toml

### ISSUE THREAD

**Issue by I-Dont-Remember** [pytest-dev/pytest-env#4]
Would love to see documentation for how to use with `pyproject.toml`, as those  seem to be growing in adoption.

Currently you can specifiy INI options in it for pytest:
```
[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "INFO"
```

Maybe it could be something like:
```
[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "INFO"
env = { ENV = "TEST", ANOTHER_VAR = "value"}
```

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by gaborbernat** [comment]
Done via https://github.com/pytest-dev/pytest-env/releases/tag/0.8.0
