### ISSUE TITLE
Use a `changelog.{md,rst}` file

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest-env#79]
This makes it easier for downstream packages to link to a range of changes.

Examples:
- https://github.com/pytest-dev/pytest-django/blob/v4.8.0/docs/changelog.rst
- https://github.com/pytest-dev/pytest/blob/8.1.1/doc/en/changelog.rst

Problem:

As a downstream package, it's nearly impossible to convey to the user changes from 0.6.2 -> 1.1.3 using GitHub releases.

**Comment by gaborbernat** [comment]
Adding good at least changelog is extra work that I'm not willing to do. Plus we have to make sure that it aligns up correctly with GitHub releases that some people prefer over changelogs. This is something I'm not willing to do for such a small project.

**Comment by gaborbernat** [comment]
> I've found it worth it for me (I also maintain a few open source packages): I frame it in terms of usefulness to downstream users and project sustainability, where the payoff is decent.

Great for you, but we don't plan to do it for now. All the best!
